name: Tests

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"
  schedule:
    - cron: "0 0 * * 0"

jobs:
  test:
    name: Test on ${{ matrix.os }}, Python ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macOS-latest, ubuntu-latest, windows-latest]
        python-version: [3.9, "3.10", "3.11"]

    steps:
      - uses: actions/checkout@v4
      - name: Additional info about the build
        shell: bash
        run: |
          uname -a
          df -h
          ulimit -a

      - uses: mamba-org/setup-micromamba@v2
        with:
          environment-file: devtools/conda-envs/test_env.yaml
          environment-name: test
          init-shell: bash
          condarc: |
            channels:
              - conda-forge
          create-args: >- 
            python=${{ matrix.python-version }}

      - name: Install package
        shell: bash -l {0}
        run: |
          python -m pip install . --no-deps
          micromamba list

      - name: Run tests
        shell: bash -l {0}
        run: |
          pytest -v --cov=CRISP --cov-report=xml --color=yes CRISP/tests/

      - name: CodeCov
        uses: codecov/codecov-action@v5
        with:
          file: ./coverage.xml
          flags: unittests
          name: codecov-${{ matrix.os }}-py${{ matrix.python-version }}

  docs:
    name: Build Documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          git+https://github.com/leonardodalinky/fpsample.git
          pip install -r docs/requirements.txt
          pip install -e .
      
      - name: Debug - Check installed packages
        run: |
          git+https://github.com/leonardodalinky/fpsample.git
          pip list | grep fpsample
          python -c "import fpsample; print('fpsample imported successfully')"
      
      - name: Build documentation
        run: |
          cd docs
          make html

  deploy_docs:
    name: Deploy Documentation to GitHub Pages
    runs-on: ubuntu-latest
    needs: docs
    if: github.ref == 'refs/heads/main'  # Only deploy on main branch
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r docs/requirements.txt
          pip install -e .
      
      - name: Build documentation
        run: |
          cd docs
          make html
      
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/_build/html